export const teamMembers = [
  {
    name: "Andreas Hofer",
    team: "Colitics",
    birthdate: "12.07.2002",
    nationality: "it",
    description: "Andreas Hofer – Silas, Coinflip Legend",
    icon: "syly.png",
  },
  {
    name: "Franz Kompatscher",
    team: "Colitics",
    birthdate: "23.06.2002",
    nationality: "it",
    description: "Franz Komposter – Sparber, Overall Legend but Zero enemies flashed",
    icon: "sparber.png",
  },
  {
    name: "Heinz-Christian Strache",
    team: "Colitics",
    birthdate: "10.09.2001",
    nationality: "at",
    description: "Heinz Christian Strache – Öma, Main AWP Player and Rageboi Nr.1",
    icon: "oemar5.png",
  },
  {
    name: "Hermann Popodi",
    team: "Colitics",
    birthdate: "08.03.2002",
    nationality: "it",
    description: "Hermann Popodi – Joni, He's just lost af",
    icon: "jonas.jpg",
  },
  {
    name: "Luis Durnwalder",
    team: "Colitics",
    birthdate: "29.09.2002",
    nationality: "it",
    description: "Luis Durnwalder – Semmel, 5€ In-Ear Headset Legend but a Beast",
    icon: "omg.png",
  },
  {
    name: "Peter Pernthaler",
    team: "Colitics",
    birthdate: "21.11.2002",
    nationality: "it",
    description: "Peter Pernthaler – Simon 2.0, Longfinger Boi and he's balliiin",
    icon: "simonn.png",
  },
  {
    name: "Philipp Achammer",
    team: "Colitics",
    birthdate: "28.03.2002",
    nationality: "it",
    description: "Philipp Achhammer – Jan, Anti-Mate Nr 1 - Whoever is above him on the scoreboard dies.",
    icon: "achhammer.jpg",
  },
  {
    name: "Stefan Unterberger",
    team: "Colitics",
    birthdate: "26.07.2001",
    nationality: "it",
    description: 'Stefan Unterberger – Manu, don’t flame him, He plays only since "2" weeks',
    icon: "unterberger.jpg",
  },
];
