export const members = [
  {
    name: "Andreas Hofer",
    short_name: "andi",
    team: "Colitics",
    birthdate: "07.12.2002",
    nationality: "it",
    description: "Andreas Hofer – Silas, Coinflip Legend",
    icon: "andi_icon.png",
    img: "andi_img.png",
    steam: "https://steamcommunity.com/profiles/76561198294451815",
  },
  {
    name: "Franz Kompatscher",
    short_name: "franz",
    team: "Colitics",
    birthdate: "06.23.2002",
    nationality: "it",
    description: "Franz Komposter – Sparber, Overall Legend but Zero enemies flashed",
    icon: "franz_icon.png",
    img: "franz_img.png",
    steam: "https://steamcommunity.com/profiles/76561198271665961",
  },
  {
    name: "Heinz-Christian Strache",
    short_name: "heinz",
    team: "Colitics",
    birthdate: "09.10.2001",
    nationality: "at",
    description: "Heinz Christian Strache – Öma, Main AWP Player and Rageboi Nr.1",
    icon: "oema_icon.png",
    img: "oema_img.png",
    steam: "https://steamcommunity.com/id/FuckOffNiggaItzPikachu",
  },
  {
    name: "Hermann Popodi",
    short_name: "hermann",
    team: "Colitics",
    birthdate: "03.08.2002",
    nationality: "it",
    description: "Hermann Popodi – Joni, He's just lost af",
    icon: "hermann_icon.jpg",
    img: "hermann_img.png",
    steam: "https://steamcommunity.com/id/Jonski321",
  },
  {
    name: "Luis Durnwalder",
    short_name: "luitl",
    team: "Colitics",
    birthdate: "09.29.2002",
    nationality: "it",
    description: "Luis Durnwalder – Semmel, 5€ In-Ear Headset Legend but a Beast",
    icon: "luitl_icon.png",
    img: "luitl_img.png",
    steam: "https://steamcommunity.com/id/dorluis/",
  },
  {
    name: "Peter Pernthaler",
    short_name: "peator",
    team: "Colitics",
    birthdate: "11.21.2002",
    nationality: "it",
    description: "Peter Pernthaler – Simon 2.0, Longfinger Boi and he's balliiin",
    icon: "peator_icon.png",
    img: "peator_img.png",
    steam: "https://steamcommunity.com/profiles/76561199018633266",
  },
  {
    name: "Philipp Achammer",
    short_name: "philipp",
    team: "Colitics",
    birthdate: "03.28.2002",
    nationality: "it",
    description: "Philipp Achhammer – Jan, Anti-Mate Nr 1 - Whoever is above him on the scoreboard dies.",
    icon: "jan_icon.jpg",
    img: "jan_img.png",
    steam: "https://steamcommunity.com/profiles/76561198345724236",
  },
  {
    name: "Stefan Unterberger",
    short_name: "stefan",
    team: "Colitics",
    birthdate: "07.26.2001",
    nationality: "it",
    description: 'Stefan Unterberger – Manu, don’t flame him, He plays only since "2" weeks',
    icon: "stefan_icon.jpg",
    img: "stefan_img.png",
    steam: "https://steamcommunity.com/profiles/76561199052057829",
  },
];
